const ACTIONS = Object.freeze({
    SET_USERS: 'SET_USERS',
    SET_USERS_ASYNC: 'SET_USERS_ASYNC',
    SET_USERS_FILTER: 'SET_USERS_FILTER',
    SIGNIN: 'SIGNIN',
    SIGNIN_ASYNC: 'SIGNIN_ASYNC',
    SIGNUP: 'SIGNUP',
    SIGNUP_ASYNC: 'SIGNUP_ASYNC',
    LOADING: 'LOADING',
})

export default ACTIONS